using VSLibrary.Controller;

namespace VSP_88D_CS.CONTROLLER.DigitalIO;

public class DeviceList
{
    public List<IAxisSettinglist> AxisSettings { get; private set; } = new List<IAxisSettinglist>();
    public List<IIOSettinglist> IOSettings { get; private set; } = new List<IIOSettinglist>();

    public DeviceList()
    {
        InitializeDefaultData();
    }

    private void InitializeDefaultData()
    {
        AxisSettings = new List<IAxisSettinglist>
        {
            new AxisSetting { ControllerType = ControllerType.Motion_AjinAXT, AxisNo = 0, AxisName = "MT00", StrAxisData = "LoadElev Z", LeadPitch = 10, PulsesPerRev = 10000, GearRatio = 1.0, PulseOutputMode = 0x4, EncInputMode = 0x3, MinSpeed = 1.0, MaxSpeed = 100, ServoEnabledReversal = false, LvSet_EndLimitP = false, LvSet_EndLimitN = false, LvSet_SlowLimitP = true, LvSet_SlowLimitN = true, LvSet_InPosition = false, LvSet_Alarm = false },
            new AxisSetting { ControllerType = ControllerType.Motion_AjinAXT, AxisNo = 1, AxisName = "MT01", StrAxisData = "LoadPush X", LeadPitch = 10, PulsesPerRev = 10000, GearRatio = 1.0, PulseOutputMode = 0x4, EncInputMode = 0x3, MinSpeed = 1.0, MaxSpeed = 100, ServoEnabledReversal = false, LvSet_EndLimitP = false, LvSet_EndLimitN = false, LvSet_SlowLimitP = true, LvSet_SlowLimitN = true, LvSet_InPosition = false, LvSet_Alarm = false },
            new AxisSetting { ControllerType = ControllerType.Motion_AjinAXT, AxisNo = 2, AxisName = "MT02", StrAxisData = "Index X", LeadPitch = 10, PulsesPerRev = 10000, GearRatio = 1.0, PulseOutputMode = 0x4, EncInputMode = 0x3, MinSpeed = 1.0, MaxSpeed = 100, ServoEnabledReversal = false, LvSet_EndLimitP = false, LvSet_EndLimitN = false, LvSet_SlowLimitP = true, LvSet_SlowLimitN = true, LvSet_InPosition = false, LvSet_Alarm = false },
            new AxisSetting { ControllerType = ControllerType.Motion_AjinAXT, AxisNo = 3, AxisName = "MT03", StrAxisData = "UnldElev Z", LeadPitch = 10, PulsesPerRev = 10000, GearRatio = 1.0, PulseOutputMode = 0x4, EncInputMode = 0x3, MinSpeed = 1.0, MaxSpeed = 100, ServoEnabledReversal = false, LvSet_EndLimitP = false, LvSet_EndLimitN = false, LvSet_SlowLimitP = true, LvSet_SlowLimitN = true, LvSet_InPosition = false, LvSet_Alarm = false },
            new AxisSetting { ControllerType = ControllerType.Motion_AjinAXT, AxisNo = 4, AxisName = "MT04", StrAxisData = "Inspect Y", LeadPitch = 25.4, PulsesPerRev = 10000, GearRatio = 1.0, PulseOutputMode = 0x4, EncInputMode = 0x3, MinSpeed = 1.0, MaxSpeed = 100, ServoEnabledReversal = true, LvSet_EndLimitP = false, LvSet_EndLimitN = false, LvSet_SlowLimitP = true, LvSet_SlowLimitN = true, LvSet_InPosition = false, LvSet_Alarm = false },
        };

        IOSettings = new List<IIOSettinglist>
        {
            new DioItem { IOType = IOType.OUTPut, WireName = "Y000", EmName = "TowerLampRed", StrdataName = "Tower Lamp Red"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y001", EmName = "TowerLampGreen", StrdataName = "Tower Lamp Green"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y002", EmName = "TowerLampYellow", StrdataName = "Tower Lamp Yellow"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y003", EmName = "Buzzer", StrdataName = "Buzzer"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y004", EmName = "VacuumPumpPowerTop", StrdataName = "Vacuum Pump Power(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y005", EmName = "VacuumPumpPowerBottom", StrdataName = "Vacuum Pump Power(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y006", EmName = "VacuumValveOpenTop", StrdataName = "Vacuum Valve Open(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y007", EmName = "VacuumValveOpenBottom", StrdataName = "Vacuum Valve Open(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y008", EmName = "Gas1InjectionTop", StrdataName = "Gas1 Injection(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y009", EmName = "Gas1InjectionBottom", StrdataName = "Gas1 Injection(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y00A", EmName = "Gas2InjectionTop", StrdataName = "Gas2 Injection(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y00B", EmName = "Gas2InjectionBottom", StrdataName = "Gas2 Injection(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y00C", EmName = "N2PurgeTop", StrdataName = "N2 Purge(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y00D", EmName = "N2PurgeBottom", StrdataName = "N2 Purge(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y00E", EmName = "AirPurgeTop", StrdataName = "Air Purge(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y00F", EmName = "AirPurgeBottom", StrdataName = "Air Purge(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y010", EmName = "GaugeProtectionValveOpenTop", StrdataName = "Gauge Protection Valve Open(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y011", EmName = "GaugeProtectionValveOpenBottom", StrdataName = "Gauge Protection Valve Open(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y012", EmName = "Spare1", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y013", EmName = "Spare2", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y014", EmName = "LoadingElevatorMgzUnclamp", StrdataName = "Loading Elevator Mgz. Unclamp"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y015", EmName = "UnloadingElevatorMgzUnclamp", StrdataName = "Unloading Elevator Mgz. Unclamp"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y016", EmName = "ChamberCloseTop"        , StrdataName = "Chamber Close(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y017", EmName = "ChamberOpenTop"         , StrdataName = "Chamber Open(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y018", EmName = "ChamberCloseBottom"     , StrdataName = "Chamber Close(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y019", EmName = "ChamberOpenBottom"      , StrdataName = "Chamber Open(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y01A", EmName = "Gas3InjectionTop"       , StrdataName = "Gas3 Injection(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y01B", EmName = "Gas3InjectionBottom"    , StrdataName = "Gas3 Injection(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y01C", EmName = "Spare3"                 , StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y01D", EmName = "Spare4"                 , StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y01E", EmName = "RfGeneratorPowerTop"    , StrdataName = "RF Generator Power(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y01F", EmName = "RfGeneratorPowerBottom" , StrdataName = "RF Generator Power(Bottom)"},

            new DioItem { IOType = IOType.OUTPut, WireName = "Y020", EmName = "ServoPower", StrdataName = "Servo Power"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y021", EmName = "ChillerPower", StrdataName = "Chiller Power"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y022", EmName = "Spare5", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y023", EmName = "Spare6", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y024", EmName = "Spare7", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y025", EmName = "DoorFrontOpen2", StrdataName = "Door Front Open2"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y026", EmName = "DoorLeftOpen2", StrdataName = "Door Left Open2"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y027", EmName = "DoorRightOpen2", StrdataName = "Door Right Open2"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y028", EmName = "LoadingConveyorCCW", StrdataName = "Loading Conveyor CCW"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y029", EmName = "LoadingConveyorRun", StrdataName = "Loading Conveyor Run"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y02A", EmName = "UnloadingConveyorRun", StrdataName = "Unloading Conveyor Run"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y02B", EmName = "ElectrodeCoolingTop", StrdataName = "Electrode Cooling(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y02C", EmName = "ElectrodeCoolingBottom", StrdataName = "Electrode Cooling(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y02D", EmName = "MatcherCoolingTop", StrdataName = "Matcher Cooling(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y02E", EmName = "MatcherCoolingBottom", StrdataName = "Matcher Cooling(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y02F", EmName = "EmptyMgzShuttleUnclamp", StrdataName = "Empty Mgz. Shuttle Unclamp"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y030", EmName = "LoadBufferCylinderTop", StrdataName = "Load Buffer Cylinder(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y031", EmName = "LoadBufferCylinderBottom", StrdataName = "Load Buffer Cylinder(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y032", EmName = "UnloadBufferCylinderTop", StrdataName = "Unload Buffer Cylinder(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y033", EmName = "UnloadBufferCylinderBottom", StrdataName = "Unload Buffer Cylinder(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y034", EmName = "PusherCylinderTop", StrdataName = "Pusher Cylinder(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y035", EmName = "PusherCylinderBottom", StrdataName = "Pusher Cylinder(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y036", EmName = "DoorFrontOpen1", StrdataName = "Door Front Open1"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y037", EmName = "DoorLeftOpen1"                      , StrdataName = "Door Left Open1"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y038", EmName = "DoorRightOpen1"                     , StrdataName = "Door Right Open1"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y039", EmName = "DoorSafety"                         , StrdataName = "Door Safety"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y03A", EmName = "Spare8"                             , StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y03B", EmName = "Spare9"                             , StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y03C", EmName = "EmptyMgzAlignerX"                   , StrdataName = "Empty Mgz. Aligner X"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y03D", EmName = "EmptyMgzAlignerY"                   , StrdataName = "Empty Mgz. Aligner Y"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y03E", EmName = "LoadingConveyorMgzAlignerExtend"    , StrdataName = "Loading Conveyor Mgz. Aligner Extend"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y03F", EmName = "UnloadingElevatorStripStopperClose" , StrdataName = "Unloading Elevator Strip Stopper Close"},

            new DioItem { IOType = IOType.OUTPut, WireName = "Y040", EmName = "Spare10", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y041", EmName = "Spare11", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y042", EmName = "Spare12", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y043", EmName = "Spare13", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y044", EmName = "UnloadingPusherDown1Top", StrdataName = "Unloading Pusher Down1(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y045", EmName = "UnloadingPusherDown2Top", StrdataName = "Unloading Pusher Down2(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y046", EmName = "UnloadingPusherDown3Top", StrdataName = "Unloading Pusher Down3(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y047", EmName = "UnloadingPusherDown4Top", StrdataName = "Unloading Pusher Down4(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y048", EmName = "UnloadingPusherDown5Top", StrdataName = "Unloading Pusher Down5(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y049", EmName = "UnloadingPusherDown6Top", StrdataName = "Unloading Pusher Down6(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y04A", EmName = "UnloadingPusherDown1Bottom", StrdataName = "Unloading Pusher Down1(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y04B", EmName = "UnloadingPusherDown2Bottom", StrdataName = "Unloading Pusher Down2(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y04C", EmName = "UnloadingPusherDown3Bottom", StrdataName = "Unloading Pusher Down3(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y04D", EmName = "UnloadingPusherDown4Bottom", StrdataName = "Unloading Pusher Down4(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y04E", EmName = "UnloadingPusherDown5Bottom", StrdataName = "Unloading Pusher Down5(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y04F", EmName = "UnloadingPusherDown6Bottom", StrdataName = "Unloading Pusher Down6(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y050", EmName = "LoadElevStripProtrusionCylExtend", StrdataName = "Load Elev. Strip Protrusion Cyl. Extend"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y051", EmName = "UnloadElevStripProtrusionCylExtend", StrdataName = "Unload Elev. Strip Protrusion Cyl. Extend"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y052", EmName = "Spare14", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y053", EmName = "Spare15", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y054", EmName = "Spare16", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y055", EmName = "Spare17", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y056", EmName = "Spare18", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y057", EmName = "Spare19", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y058", EmName = "Spare20", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y059", EmName = "Spare21", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y05A", EmName = "Spare22", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y05B", EmName = "Spare23", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y05C", EmName = "Spare24", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y05D", EmName = "RfOnTimerTop", StrdataName = "RF On Timer(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y05E", EmName = "RfOnTimerBottom", StrdataName = "RF On Timer(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "Y05F", EmName = "LoadingElevatorStripStopperClose", StrdataName = "Loading Elevator Strip Stopper Close"},

            new DioItem { IOType = IOType.InPut, WireName = "X000", EmName = "LeftEmergency", StrdataName = "Left Emergency"},
            new DioItem { IOType = IOType.InPut, WireName = "X001", EmName = "RightEmergency", StrdataName = "Right Emergency"},
            new DioItem { IOType = IOType.InPut, WireName = "X002", EmName = "RearEmergency", StrdataName = "Rear Emergency"},
            new DioItem { IOType = IOType.InPut, WireName = "X003", EmName = "FrontSafetyDoor", StrdataName = "Front Safety Door"},
            new DioItem { IOType = IOType.InPut, WireName = "X004", EmName = "LeftSafetyDoor", StrdataName = "Left Safety Door"},
            new DioItem { IOType = IOType.InPut, WireName = "X005", EmName = "RightSafetyDoor", StrdataName = "Right Safety Door"},
            new DioItem { IOType = IOType.InPut, WireName = "X006", EmName = "VacuumValveOpenTop", StrdataName = "Vacuum Valve Open(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X007", EmName = "VacuumValveOpenBottom", StrdataName = "Vacuum Valve Open(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X008", EmName = "Gas1Pressure", StrdataName = "Gas1 Pressure"},
            new DioItem { IOType = IOType.InPut, WireName = "X009", EmName = "Gas2PressureOption", StrdataName = "Gas2 Pressure(Option)"},
            new DioItem { IOType = IOType.InPut, WireName = "X00A", EmName = "PumpOverloadTop", StrdataName = "Pump Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X00B", EmName = "PumpOverloadBottom", StrdataName = "Pump Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X00C", EmName = "PumpOilCheckTop", StrdataName = "Pump Oil Check(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X00D", EmName = "PumpOilCheckBottom", StrdataName = "Pump Oil Check(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X00E", EmName = "LoadingElevatorMgzClampDown", StrdataName = "Loading Elevator Mgz. Clamp Down"},
            new DioItem { IOType = IOType.InPut, WireName = "X00F", EmName = "LoadingElevatorMgzClampUp", StrdataName = "Loading Elevator Mgz. Clamp Up"},
            new DioItem { IOType = IOType.InPut, WireName = "X010", EmName = "UnloadingElevatorMgzClampDown", StrdataName = "Unloading Elevator Mgz. Clamp Down"},
            new DioItem { IOType = IOType.InPut, WireName = "X011", EmName = "UnloadingElevatorMgzClampUp", StrdataName = "Unloading Elevator Mgz. Clamp Up"},
            new DioItem { IOType = IOType.InPut, WireName = "X012", EmName = "MainAirPressure", StrdataName = "Main Air Pressure"},
            new DioItem { IOType = IOType.InPut, WireName = "X013", EmName = "Gas3PressureOption", StrdataName = "Gas3 Pressure(Option)"},
            new DioItem { IOType = IOType.InPut, WireName = "X014", EmName = "ChillerFlowDetectTop", StrdataName = "Chiller Flow Detect(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X015", EmName = "ChillerFlowDetectBottom", StrdataName = "Chiller Flow Detect(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X016", EmName = "LoadingElevatorMgzDetect1", StrdataName = "Loading Elevator Mgz. Detect 1"},
            new DioItem { IOType = IOType.InPut, WireName = "X017", EmName = "LoadingElevatorMgzDetect2", StrdataName = "Loading Elevator Mgz. Detect 2"},
            new DioItem { IOType = IOType.InPut, WireName = "X018", EmName = "UnloadingElevatorMgzDetect1", StrdataName = "Unloading Elevator Mgz. Detect 1"},
            new DioItem { IOType = IOType.InPut, WireName = "X019", EmName = "UnloadingElevatorMgzDetect2", StrdataName = "Unloading Elevator Mgz. Detect 2"},
            new DioItem { IOType = IOType.InPut, WireName = "X01A", EmName = "LoadingConveyorMgzInDetect", StrdataName = "Loading Conveyor Mgz. In Detect"},
            new DioItem { IOType = IOType.InPut, WireName = "X01B", EmName = "LoadingConveyorMgzArrivalDetect", StrdataName = "Loading Conveyor Mgz. Arrival Detect"},
            new DioItem { IOType = IOType.InPut, WireName = "X01C", EmName = "EmptyMgzAlignerCloseCheck1", StrdataName = "Empty Mgz. Aligner Close Check 1"},
            new DioItem { IOType = IOType.InPut, WireName = "X01D", EmName = "EmptyMgzAlignerCloseCheck2", StrdataName = "Empty Mgz. Aligner Close Check 2"},
            new DioItem { IOType = IOType.InPut, WireName = "X01E", EmName = "EmptyMgzAlignerMgzDetect", StrdataName = "Empty Mgz. Aligner Mgz. Detect"},
            new DioItem { IOType = IOType.InPut, WireName = "X01F", EmName = "UnloadingConveyorMgzArrivalDetect", StrdataName = "Unloading Conveyor Mgz. Arrival Detect"},

            new DioItem { IOType = IOType.InPut, WireName = "X020", EmName = "UnloadingConveyorMgzFullCheck1", StrdataName = "Unloading Conveyor Mgz. Full Check 1"},
            new DioItem { IOType = IOType.InPut, WireName = "X021", EmName = "UnloadingConveyorMgzFullCheck2", StrdataName = "Unloading Conveyor Mgz. Full Check 2"},
            new DioItem { IOType = IOType.InPut, WireName = "X022", EmName = "UnloadingConveyorMgzInDetect", StrdataName = "Unloading Conveyor Mgz. In Detect"},
            new DioItem { IOType = IOType.InPut, WireName = "X023", EmName = "LoadingPusherOverloadTop", StrdataName = "Loading Pusher Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X024", EmName = "LoadingPusherOverloadBottom", StrdataName = "Loading Pusher Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X025", EmName = "LoadingIndexOverloadTop", StrdataName = "Loading Index Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X026", EmName = "LoadingIndexOverloadBottom", StrdataName = "Loading Index Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X027", EmName = "LoadingMgzWidth", StrdataName = "Loading Mgz Width"},
            new DioItem { IOType = IOType.InPut, WireName = "X028", EmName = "UnloadingMgzWidth", StrdataName = "Unloading Mgz Width"},
            new DioItem { IOType = IOType.InPut, WireName = "X029", EmName = "EmptyMgzShuttleMgzDetect", StrdataName = "Empty Mgz. Shuttle Mgz. Detect"},
            new DioItem { IOType = IOType.InPut, WireName = "X02A", EmName = "LoadingRailLeftTop", StrdataName = "Loading Rail Left(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X02B", EmName = "LoadingRailRightTop", StrdataName = "Loading Rail Right(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X02C", EmName = "LoadingRailLeftBottom", StrdataName = "Loading Rail Left(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X02D", EmName = "LoadingRailRightBottom", StrdataName = "Loading Rail Right(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X02E", EmName = "ChamberOpenTop", StrdataName = "Chamber Open(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X02F", EmName = "ChamberCloseTop", StrdataName = "Chamber Close(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X030", EmName = "ChamberOpenBottom", StrdataName = "Chamber Open(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X031", EmName = "ChamberCloseBottom", StrdataName = "Chamber Close(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X032", EmName = "LoadingIndexUp1Top", StrdataName = "Loading Index Up 1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X033", EmName = "LoadingIndexDown1Top", StrdataName = "Loading Index Down 1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X034", EmName = "LoadingIndexUp1Bottom", StrdataName = "Loading Index Up 1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X035", EmName = "LoadingIndexDown1Bottom", StrdataName = "Loading Index Down 1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X036", EmName = "LoadingIndexReadyPositionTop", StrdataName = "Loading Index Ready Position(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X037", EmName = "LoadingIndexReadyPositionBottom", StrdataName = "Loading Index Ready Position(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X038", EmName = "UnloadingIndexReadyPositionTop", StrdataName = "Unloading Index Ready Position(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X039", EmName = "UnloadingIndexReadyPositionBottom", StrdataName = "Unloading Index Ready Position(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X03A", EmName = "PusherReadyPositionTop", StrdataName = "Pusher Ready Position(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X03B", EmName = "PusherReadyPositionBottom", StrdataName = "Pusher Ready Position(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X03C", EmName = "UnloadingRailRightTop", StrdataName = "Unloading Rail Right(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X03D", EmName = "UnloadingRailLeftTop", StrdataName = "Unloading Rail Left(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X03E", EmName = "UnloadingRailRightBottom", StrdataName = "Unloading Rail Right(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X03F", EmName = "UnloadingRailLeftBottom", StrdataName = "Unloading Rail Left(Bottom)"},

            new DioItem { IOType = IOType.InPut, WireName = "X040", EmName = "UnloadingConveyorSafetyCheck2", StrdataName = "Unloading Conveyor Safety Check 2"},
            new DioItem { IOType = IOType.InPut, WireName = "X041", EmName = "UnloadingConveyorSafetyCheck3", StrdataName = "Unloading Conveyor Safety Check 3"},
            new DioItem { IOType = IOType.InPut, WireName = "X042", EmName = "PusherStripDetectTop", StrdataName = "Pusher Strip Detect(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X043", EmName = "PusherStripDetectBottom", StrdataName = "Pusher Strip Detect(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X044", EmName = "ElectrodeCoolingTop", StrdataName = "Electrode Cooling(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X045", EmName = "ElectrodeCoolingBottom", StrdataName = "Electrode Cooling(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X046", EmName = "MatcherCoolingTop", StrdataName = "Matcher Cooling(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X047", EmName = "MatcherCoolingBottom", StrdataName = "Matcher Cooling(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X048", EmName = "EmptyMgzAlignerXExtend", StrdataName = "Empty Mgz. Aligner X Extend"},
            new DioItem { IOType = IOType.InPut, WireName = "X049", EmName = "EmptyMgzAlignerXRetract", StrdataName = "Empty Mgz. Aligner X Retract"},
            new DioItem { IOType = IOType.InPut, WireName = "X04A", EmName = "EmptyMgzAlignerYExtend", StrdataName = "Empty Mgz. Aligner Y Extend"},
            new DioItem { IOType = IOType.InPut, WireName = "X04B", EmName = "EmptyMgzAlignerYRetract", StrdataName = "Empty Mgz. Aligner Y Retract"},
            new DioItem { IOType = IOType.InPut, WireName = "X04C", EmName = "LoadingConveyorMgzAlignerExtend", StrdataName = "Loading Conveyor Mgz. Aligner Extend"},
            new DioItem { IOType = IOType.InPut, WireName = "X04D", EmName = "LoadingConveyorMgzAlignerRetract", StrdataName = "Loading Conveyor Mgz. Aligner Retract"},
            new DioItem { IOType = IOType.InPut, WireName = "X04E", EmName = "UnloadingElevatorStripStopperClose", StrdataName = "Unloading Elevator Strip Stopper Close"},
            new DioItem { IOType = IOType.InPut, WireName = "X04F", EmName = "UnloadingElevatorStripStopperOpen", StrdataName = "Unloading Elevator Strip Stopper Open"},
            new DioItem { IOType = IOType.InPut, WireName = "X050", EmName = "EmptyMgzShuttleClampClose", StrdataName = "Empty Mgz. Shuttle Clamp Close"},
            new DioItem { IOType = IOType.InPut, WireName = "X051", EmName = "EmptyMgzShuttleClampOpen", StrdataName = "Empty Mgz. Shuttle Clamp Open"},
            new DioItem { IOType = IOType.InPut, WireName = "X052", EmName = "LoadingRailInStripEdgeDetect", StrdataName = "Loading Rail In Strip Edge Detect"},
            new DioItem { IOType = IOType.InPut, WireName = "X053", EmName = "LoadingRailRightStripDetect1Top", StrdataName = "Loading Rail Right Strip Detect 1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X054", EmName = "LoadingRailRightStripDetect2Top", StrdataName = "Loading Rail Right Strip Detect 2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X055", EmName = "LoadingRailRightStripDetect3Top", StrdataName = "Loading Rail Right Strip Detect 3(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X056", EmName = "LoadingRailRightStripDetect4Top", StrdataName = "Loading Rail Right Strip Detect 4(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X057", EmName = "LoadingRailRightStripDetect5Top", StrdataName = "Loading Rail Right Strip Detect 5(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X058", EmName = "LoadingRailRightStripDetect6Top", StrdataName = "Loading Rail Right Strip Detect 6(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X059", EmName = "LoadingRailOutStripEdgeDetectTop", StrdataName = "Loading Rail Out Strip Edge Detect(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X05A", EmName = "UnloadingRailInStripEdgeDetectTop", StrdataName = "Unloading Rail In Strip Edge Detect(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X05B", EmName = "UnloadingRailRightStripDetect1Top", StrdataName = "Unloading Rail Right Strip Detect 1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X05C", EmName = "UnloadingRailRightStripDetect2Top", StrdataName = "Unloading Rail Right Strip Detect 2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X05D", EmName = "UnloadingRailRightStripDetect3Top", StrdataName = "Unloading Rail Right Strip Detect 3(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X05E", EmName = "UnloadingRailRightStripDetect4Top", StrdataName = "Unloading Rail Right Strip Detect 4(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X05F", EmName = "UnloadingRailRightStripDetect5Top", StrdataName = "Unloading Rail Right Strip Detect 5(Top)"},

            new DioItem { IOType = IOType.InPut, WireName = "X060", EmName = "UnloadingRailRightStripDetect6Top", StrdataName = "Unloading Rail Right Strip Detect 6(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X061", EmName = "UnloadingRailRightStripDetect7Top", StrdataName = "Unloading Rail Right Strip Detect 7(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X062", EmName = "Spare25", StrdataName = "Spare"},
            new DioItem { IOType = IOType.InPut, WireName = "X063", EmName = "LoadingRailInStripEdgeDetectBottom", StrdataName = "Loading Rail In Strip Edge Detect(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X064", EmName = "LoadingRailRightStripDetect1Bottom", StrdataName = "Loading Rail Right Strip Detect 1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X065", EmName = "LoadingRailRightStripDetect2Bottom", StrdataName = "Loading Rail Right Strip Detect 2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X066", EmName = "LoadingRailRightStripDetect3Bottom", StrdataName = "Loading Rail Right Strip Detect 3(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X067", EmName = "LoadingRailRightStripDetect4Bottom", StrdataName = "Loading Rail Right Strip Detect 4(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X068", EmName = "LoadingRailRightStripDetect5Bottom", StrdataName = "Loading Rail Right Strip Detect 5(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X069", EmName = "LoadingRailRightStripDetect6Bottom", StrdataName = "Loading Rail Right Strip Detect 6(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X06A", EmName = "LoadingRailOutStripEdgeDetectBottom", StrdataName = "Loading Rail Out Strip Edge Detect(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X06B", EmName = "ChamberOutStripDetectBottom", StrdataName = "Chamber Out Strip Detect(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X06C", EmName = "UnloadingRailRightStripDetect1Bottom", StrdataName = "Unloading Rail Right Strip Detect 1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X06D", EmName = "UnloadingRailRightStripDetect2Bottom", StrdataName = "Unloading Rail Right Strip Detect 2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X06E", EmName = "UnloadingRailRightStripDetect3Bottom", StrdataName = "Unloading Rail Right Strip Detect 3(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X06F", EmName = "UnloadingRailRightStripDetect4Bottom", StrdataName = "Unloading Rail Right Strip Detect 4(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X070", EmName = "UnloadingRailRightStripDetect5Bottom", StrdataName = "Unloading Rail Right Strip Detect 5(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X071", EmName = "UnloadingRailRightStripDetect6Bottom", StrdataName = "Unloading Rail Right Strip Detect 6(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X072", EmName = "UnloadingElevInStripDetectBottom", StrdataName = "Unloading Elev. In Strip Detect(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X073", EmName = "DoorLockCylinderTop", StrdataName = "Door Lock Cylinder(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X074", EmName = "UnloadingPusher1UpTop", StrdataName = "Unloading Pusher1 Up(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X075", EmName = "UnloadingPusher1DownTop", StrdataName = "Unloading Pusher1 Down(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X076", EmName = "UnloadingPusher2UpTop", StrdataName = "Unloading Pusher2 Up(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X077", EmName = "UnloadingPusher2DownTop", StrdataName = "Unloading Pusher2 Down(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X078", EmName = "UnloadingPusher3UpTop", StrdataName = "Unloading Pusher3 Up(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X079", EmName = "UnloadingPusher3DownTop", StrdataName = "Unloading Pusher3 Down(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X07A", EmName = "UnloadingPusher4UpTop", StrdataName = "Unloading Pusher4 Up(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X07B", EmName = "UnloadingPusher4DownTop", StrdataName = "Unloading Pusher4 Down(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X07C", EmName = "UnloadingPusher5UpTop", StrdataName = "Unloading Pusher5 Up(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X07D", EmName = "UnloadingPusher5DownTop", StrdataName = "Unloading Pusher5 Down(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X07E", EmName = "UnloadingPusher6UpTop", StrdataName = "Unloading Pusher6 Up(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X07F", EmName = "UnloadingPusher6DownTop", StrdataName = "Unloading Pusher6 Down(Top)"},

            new DioItem { IOType = IOType.InPut, WireName = "X080", EmName = "UnloadingPusher1UpBottom", StrdataName = "Unloading Pusher1 Up(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X081", EmName = "UnloadingPusher1DownBottom", StrdataName = "Unloading Pusher1 Down(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X082", EmName = "UnloadingPusher2UpBottom", StrdataName = "Unloading Pusher2 Up(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X083", EmName = "UnloadingPusher2DownBottom", StrdataName = "Unloading Pusher2 Down(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X084", EmName = "UnloadingPusher3UpBottom", StrdataName = "Unloading Pusher3 Up(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X085", EmName = "UnloadingPusher3DownBottom", StrdataName = "Unloading Pusher3 Down(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X086", EmName = "UnloadingPusher4UpBottom", StrdataName = "Unloading Pusher4 Up(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X087", EmName = "UnloadingPusher4DownBottom", StrdataName = "Unloading Pusher4 Down(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X088", EmName = "UnloadingPusher5UpBottom", StrdataName = "Unloading Pusher5 Up(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X089", EmName = "UnloadingPusher5DownBottom", StrdataName = "Unloading Pusher5 Down(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X08A", EmName = "UnloadingPusher6UpBottom", StrdataName = "Unloading Pusher6 Up(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X08B", EmName = "UnloadingPusher6DownBottom", StrdataName = "Unloading Pusher6 Down(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X08C", EmName = "LoadingConveyorSafetyCheck3", StrdataName = "Loading Conveyor Safety Check 3"},
            new DioItem { IOType = IOType.InPut, WireName = "X08D", EmName = "LoadingConveyorSafetyCheck2", StrdataName = "Loading Conveyor Safety Check 2"},
            new DioItem { IOType = IOType.InPut, WireName = "X08E", EmName = "UnloadingConveyorSafetyCheck1", StrdataName = "Unloading Conveyor Safety Check 1"},
            new DioItem { IOType = IOType.InPut, WireName = "X08F", EmName = "LoadingConveyorSafetyCheck1", StrdataName = "Loading Conveyor Safety Check 1"},
            new DioItem { IOType = IOType.InPut, WireName = "X090", EmName = "LoadingRailLeftStripDetect1Top", StrdataName = "Loading Rail Left Strip Detect 1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X091", EmName = "LoadingRailLeftStripDetect2Top", StrdataName = "Loading Rail Left Strip Detect 2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X092", EmName = "LoadingRailLeftStripDetect3Top", StrdataName = "Loading Rail Left Strip Detect 3(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X093", EmName = "LoadingRailLeftStripDetect4Top", StrdataName = "Loading Rail Left Strip Detect 4(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X094", EmName = "LoadingRailLeftStripDetect5Top", StrdataName = "Loading Rail Left Strip Detect 5(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X095", EmName = "LoadingRailLeftStripDetect6Top", StrdataName = "Loading Rail Left Strip Detect 6(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X096", EmName = "LoadingRailLeftStripDetect1Bottom", StrdataName = "Loading Rail Left Strip Detect 1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X097", EmName = "LoadingRailLeftStripDetect2Bottom", StrdataName = "Loading Rail Left Strip Detect 2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X098", EmName = "LoadingRailLeftStripDetect3Bottom", StrdataName = "Loading Rail Left Strip Detect 3(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X099", EmName = "LoadingRailLeftStripDetect4Bottom", StrdataName = "Loading Rail Left Strip Detect 4(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X09A", EmName = "LoadingRailLeftStripDetect5Bottom", StrdataName = "Loading Rail Left Strip Detect 5(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X09B", EmName = "LoadingRailLeftStripDetect6Bottom", StrdataName = "Loading Rail Left Strip Detect 6(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X09C", EmName = "UnloadingRailLeftStripDetect1Top", StrdataName = "Unloading Rail Left Strip Detect 1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X09D", EmName = "UnloadingRailLeftStripDetect2Top", StrdataName = "Unloading Rail Left Strip Detect 2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X09E", EmName = "UnloadingRailLeftStripDetect3Top", StrdataName = "Unloading Rail Left Strip Detect 3(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X09F", EmName = "UnloadingRailLeftStripDetect4Top", StrdataName = "Unloading Rail Left Strip Detect 4(Top)"},

            new DioItem { IOType = IOType.InPut, WireName = "X0A0", EmName = "UnloadingRailLeftStripDetect5Top", StrdataName = "Unloading Rail Left Strip Detect 5(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A1", EmName = "UnloadingRailLeftStripDetect6Top", StrdataName = "Unloading Rail Left Strip Detect 6(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A2", EmName = "UnloadingRailLeftStripDetect1Bottom", StrdataName = "Unloading Rail Left Strip Detect 1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A3", EmName = "UnloadingRailLeftStripDetect2Bottom", StrdataName = "Unloading Rail Left Strip Detect 2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A4", EmName = "UnloadingRailLeftStripDetect3Bottom", StrdataName = "Unloading Rail Left Strip Detect 3(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A5", EmName = "UnloadingRailLeftStripDetect4Bottom", StrdataName = "Unloading Rail Left Strip Detect 4(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A6", EmName = "UnloadingRailLeftStripDetect5Bottom", StrdataName = "Unloading Rail Left Strip Detect 5(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A7", EmName = "UnloadingRailLeftStripDetect6Bottom", StrdataName = "Unloading Rail Left Strip Detect 6(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A8", EmName = "UnloadingIndex1OverloadTop", StrdataName = "Unloading Index1 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0A9", EmName = "UnloadingIndex2OverloadTop", StrdataName = "Unloading Index2 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0AA", EmName = "UnloadingIndex3OverloadTop", StrdataName = "Unloading Index3 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0AB", EmName = "UnloadingIndex4OverloadTop", StrdataName = "Unloading Index4 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0AC", EmName = "UnloadingIndex5OverloadTop", StrdataName = "Unloading Index5 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0AD", EmName = "UnloadingIndex6OverloadTop", StrdataName = "Unloading Index6 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0AE", EmName = "UnloadingIndex1OverloadBottom", StrdataName = "Unloading Index1 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0AF", EmName = "UnloadingIndex2OverloadBottom", StrdataName = "Unloading Index2 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B0", EmName = "UnloadingIndex3OverloadBottom", StrdataName = "Unloading Index3 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B1", EmName = "UnloadingIndex4OverloadBottom", StrdataName = "Unloading Index4 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B2", EmName = "UnloadingIndex5OverloadBottom", StrdataName = "Unloading Index5 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B3", EmName = "UnloadingIndex6OverloadBottom", StrdataName = "Unloading Index6 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B4", EmName = "LoadingIndex2OverloadTop", StrdataName = "Loading Index2 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B5", EmName = "LoadingIndex3OverloadTop", StrdataName = "Loading Index3 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B6", EmName = "LoadingIndex4OverloadTop", StrdataName = "Loading Index4 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B7", EmName = "LoadingIndex5OverloadTop", StrdataName = "Loading Index5 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B8", EmName = "LoadingIndex6OverloadTop", StrdataName = "Loading Index6 Overload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0B9", EmName = "LoadingIndex2OverloadBottom", StrdataName = "Loading Index2 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0BA", EmName = "LoadingIndex3OverloadBottom", StrdataName = "Loading Index3 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0BB", EmName = "LoadingIndex4OverloadBottom", StrdataName = "Loading Index4 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0BC", EmName = "LoadingIndex5OverloadBottom", StrdataName = "Loading Index5 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0BD", EmName = "LoadingIndex6OverloadBottom", StrdataName = "Loading Index6 Overload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName = "X0BE", EmName = "LoadConveyorCcwSwitch", StrdataName = "Load Conveyor Ccw Switch"},
            new DioItem { IOType = IOType.InPut, WireName = "X0BF", EmName = "DoorLockCylinderBottom", StrdataName = "Door Lock Cylinder(Bottom)"},

            new DioItem { IOType = IOType.InPut, WireName = "AO000", EmName = "Output_Ch01", StrdataName = "Chanl 01"},
            new DioItem { IOType = IOType.InPut, WireName = "AO001", EmName = "Output_Ch02", StrdataName = "Chanl 02"},
            new DioItem { IOType = IOType.InPut, WireName = "AO002", EmName = "Output_Ch03", StrdataName = "Chanl 03"},
            new DioItem { IOType = IOType.InPut, WireName = "AO003", EmName = "Output_Ch04", StrdataName = "Chanl 04"},

            new DioItem { IOType = IOType.InPut, WireName = "AI000", EmName = "Input_Ch01", StrdataName = "Chanl 01"},
            new DioItem { IOType = IOType.InPut, WireName = "AI001", EmName = "Input_Ch02", StrdataName = "Chanl 02"},
            new DioItem { IOType = IOType.InPut, WireName = "AI002", EmName = "Input_Ch03", StrdataName = "Chanl 03"},
            new DioItem { IOType = IOType.InPut, WireName = "AI003", EmName = "Input_Ch04", StrdataName = "Chanl 04"},
            new DioItem { IOType = IOType.InPut, WireName = "AI004", EmName = "Input_Ch05", StrdataName = "Chanl 05"},
            new DioItem { IOType = IOType.InPut, WireName = "AI005", EmName = "Input_Ch06", StrdataName = "Chanl 06"},
            new DioItem { IOType = IOType.InPut, WireName = "AI006", EmName = "Input_Ch07", StrdataName = "Chanl 07"},
            new DioItem { IOType = IOType.InPut, WireName = "AI007", EmName = "Input_Ch08", StrdataName = "Chanl 08"},

            new DioItem { IOType = IOType.InPut, WireName ="MX000", EmName ="Spare26", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX001", EmName ="Spare27", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX002", EmName ="LoadIndexStripPosCheck1_1_Top", StrdataName ="Load Index Strip Pos. Check1_1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX003", EmName ="LoadIndexStripPosCheck1_2_Top", StrdataName ="Load Index Strip Pos. Check1_2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX004", EmName ="LoadIndexStripPosCheck3_1_Top", StrdataName ="Load Index Strip Pos. Check3_1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX005", EmName ="LoadElevMgzStripProtrusionDetect", StrdataName ="Load Elev. Mgz Strip Protrusion Detect"},
            new DioItem { IOType = IOType.InPut, WireName ="MX006", EmName ="Spare28", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX007", EmName ="Spare29", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX008", EmName ="Spare30", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX009", EmName ="Spare31", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX00A", EmName ="LoadIndexStripPosCheck2_1_Top", StrdataName ="Load Index Strip Pos. Check2_1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX00B", EmName ="LoadIndexStripPosCheck2_2_Top", StrdataName ="Load Index Strip Pos. Check2_2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX00C", EmName ="LoadIndexStripPosCheck3_2_Top", StrdataName ="Load Index Strip Pos. Check3_2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX00D", EmName ="Spare32", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX00E", EmName ="Spare33", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX00F", EmName ="Spare34", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX010", EmName ="Spare35", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX011", EmName ="Spare36", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX012", EmName ="LoadIndexStripPosCheck1_1_Bottom", StrdataName ="Load Index Strip Pos. Check1_1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX013", EmName ="LoadIndexStripPosCheck1_2_Bottom", StrdataName ="Load Index Strip Pos. Check1_2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX014", EmName ="LoadIndexStripPosCheck3_1_Bottom", StrdataName ="Load Index Strip Pos. Check3_1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX015", EmName ="UnloadElevMgzStripProtrusionDetect", StrdataName ="Unload Elev. Mgz Strip Protrusion Detec"},
            new DioItem { IOType = IOType.InPut, WireName ="MX016", EmName ="Spare37", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX017", EmName ="Spare38", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX018", EmName ="Spare39", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX019", EmName ="Spare40", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX01A", EmName ="LoadIndexStripPosCheck2_1_Bottom", StrdataName ="Load Index Strip Pos. Check2_1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX01B", EmName ="LoadIndexStripPosCheck2_2_Bottom", StrdataName ="Load Index Strip Pos. Check2_2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX01C", EmName ="LoadIndexStripPosCheck3_2_Bottom", StrdataName ="Load Index Strip Pos. Check3_2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX01D", EmName ="Spare41", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX01E", EmName ="Spare42", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX01F", EmName ="Spare43", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX020", EmName ="Spare44", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX021", EmName ="Spare45", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX022", EmName ="IonizerAlarmLoad_Top", StrdataName ="Ionizer Alarm Load(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX023", EmName ="IonizerAlarmLoad_Bottom", StrdataName ="Ionizer Alarm Load(Bottm)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX024", EmName ="IonizerAlarmUnload_Top", StrdataName ="Ionizer Alarm Unload(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX025", EmName ="Spare46", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX026", EmName ="Spare47", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX027", EmName ="Spare48", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX028", EmName ="Spare49", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX029", EmName ="Spare50", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX02A", EmName ="IonizerAlarmUnload_Bottom", StrdataName ="Ionizer Alarm Unload(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX02B", EmName ="Spare51", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX02C", EmName ="Spare52", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX02D", EmName ="Spare53", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX02E", EmName ="Spare54", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX02F", EmName ="Spare55", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX030", EmName ="Spare56", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX031", EmName ="Spare57", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX032", EmName ="LoadMgzEndBarClose", StrdataName ="Load Mgz. End-Bar Close"},
            new DioItem { IOType = IOType.InPut, WireName ="MX033", EmName ="LoadMgzEndBarOpen", StrdataName ="Load Mgz. End-Bar Open"},
            new DioItem { IOType = IOType.InPut, WireName ="MX034", EmName ="Spare58", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX035", EmName ="Spare59", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX036", EmName ="Spare60", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX037", EmName ="Spare61", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX038", EmName ="Spare62", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX039", EmName ="Spare63", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX03A", EmName ="LoadElevStripProtrusionCylExtend", StrdataName ="Load Elev Strip Protrusion Cyl. Extend"},
            new DioItem { IOType = IOType.InPut, WireName ="MX03B", EmName ="LoadElevStripProtrusionCylRetract", StrdataName ="Load Elev Strip Protrusion Cyl. Retract"},
            new DioItem { IOType = IOType.InPut, WireName ="MX03C", EmName ="UnloadElevStripProtrusionCylExtend", StrdataName ="Unload Elev. Strip Protrusion Cyl. Exte"},
            new DioItem { IOType = IOType.InPut, WireName ="MX03D", EmName ="UnloadElevStripProtrusionCylRetract", StrdataName ="Unload Elev. Strip Protrusion Cyl. Retr"},
            new DioItem { IOType = IOType.InPut, WireName ="MX03E", EmName ="Spare64", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX03F", EmName ="Spare65", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX040", EmName ="Spare66", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX041", EmName ="Spare67", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX042", EmName ="Spare68", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX043", EmName ="UnloadMgzStripScan", StrdataName ="Unload Mgz. Strip Scan"},
            new DioItem { IOType = IOType.InPut, WireName ="MX044", EmName ="LoadStripTurnOver1_Top", StrdataName ="Load Strip Turn Over 1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX045", EmName ="LoadStripTurnOver2_Top", StrdataName ="Load Strip Turn Over 2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX046", EmName ="Spare69", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX047", EmName ="Spare70", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX048", EmName ="Spare71", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX049", EmName ="Spare72", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX04A", EmName ="LoadStripTurnOver3_Top", StrdataName ="Load Strip Turn Over 3(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX04B", EmName ="LoadStripTurnOver4_Top", StrdataName ="Load Strip Turn Over 4(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX04C", EmName ="LoadStripTurnOver5_Top", StrdataName ="Load Strip Turn Over 5(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX04D", EmName ="LoadStripTurnOver6_Top", StrdataName ="Load Strip Turn Over 6(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX04E", EmName ="Spare73", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX04F", EmName ="Spare74", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX050", EmName ="Spare75", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX051", EmName ="Spare76", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX052", EmName ="LoadStripTurnOver1_Bottom", StrdataName ="Load Strip Turn Over 1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX053", EmName ="LoadStripTurnOver2_Bottom", StrdataName ="Load Strip Turn Over 2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX054", EmName ="LoadStripTurnOver3_Bottom", StrdataName ="Load Strip Turn Over 3(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX055", EmName ="LoadStripTurnOver4_Bottom", StrdataName ="Load Strip Turn Over 4(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX056", EmName ="Spare77", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX057", EmName ="Spare78", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX058", EmName ="Spare79", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX059", EmName ="Spare80", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX05A", EmName ="LoadStripTurnOver5_Bottom", StrdataName ="Load Strip Turn Over 5(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX05B", EmName ="LoadStripTurnOver6_Bottom", StrdataName ="Load Strip Turn Over 6(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX05C", EmName ="LoadMgzHandleDetect", StrdataName ="Load Mgz. Handle Detect"},
            new DioItem { IOType = IOType.InPut, WireName ="MX05D", EmName ="UnloadMgzHandleDetect", StrdataName ="Unload Mgz. Handle Detect"},
            new DioItem { IOType = IOType.InPut, WireName ="MX05E", EmName ="Spare81", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX05F", EmName ="Spare82", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX060", EmName ="Spare83", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX061", EmName ="Spare84", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX062", EmName ="LoadIndexStripPosCheck4_1_Top", StrdataName ="Load Index Strip Pos. Check4_1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX063", EmName ="LoadIndexStripPosCheck4_2_Top", StrdataName ="Load Index Strip Pos. Check4_2(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX064", EmName ="Spare85", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX065", EmName ="Spare86", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX066", EmName ="Spare87", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX067", EmName ="Spare88", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX068", EmName ="Spare89", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX069", EmName ="Spare90", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX06A", EmName ="Spare91", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX06B", EmName ="Spare92", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX06C", EmName ="Spare93", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX06D", EmName ="Spare94", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX06E", EmName ="Spare95", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX06F", EmName ="Spare96", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX070", EmName ="Spare97", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX071", EmName ="Spare98", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX072", EmName ="LoadIndexStripPosCheck4_1_Bottom", StrdataName ="Load Index Strip Pos. Check4_1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX073", EmName ="LoadIndexStripPosCheck4_2_Bottom", StrdataName ="Load Index Strip Pos. Check4_2(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX074", EmName ="LoadConvMgzEndBarDetect", StrdataName ="Load Conv. Mgz. End-Bar Detect"},
            new DioItem { IOType = IOType.InPut, WireName ="MX075", EmName ="Spare99", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX076", EmName ="Spare100", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX077", EmName ="Spare101", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX078", EmName ="Spare102", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX079", EmName ="Spare103", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX07A", EmName ="LoadIndexStripPosCheck1_1_Top", StrdataName ="Load Index Strip Pos. Check1_1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX07B", EmName ="LoadIndexStripPosCheck2_1_Top", StrdataName ="Load Index Strip Pos. Check2_1(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX07C", EmName ="LoadIndexStripPosCheck1_1_Bottom", StrdataName ="Load Index Strip Pos. Check1_1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX07D", EmName ="LoadIndexStripPosCheck2_1_Bottom", StrdataName ="Load Index Strip Pos. Check2_1(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX07E", EmName ="Spare104", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX07F", EmName ="Spare105", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX080", EmName ="Spare106", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX081", EmName ="Spare107", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX082", EmName ="LoadingPusherOverloadDual_Top", StrdataName ="Loading Pusher Overload Dual(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX083", EmName ="LoadingPusherOverloadDual_Bottom", StrdataName ="Loading Pusher Overload Dual(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX084", EmName ="LoadingElevatorMgzFootSingle", StrdataName ="Loading Elevator Mgz. Foot WorkSingle"},
            new DioItem { IOType = IOType.InPut, WireName ="MX085", EmName ="LoadingElevatorMgzFootDual", StrdataName ="Loading Elevator Mgz. Foot Dual"},
            new DioItem { IOType = IOType.InPut, WireName ="MX086", EmName ="Spare108", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX087", EmName ="Spare109", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX088", EmName ="Spare110", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX089", EmName ="Spare111", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX08A", EmName ="UnloadingElevatorMgzFootSingle", StrdataName ="Unloading Elevator Mgz. Foot WorkSingle"},
            new DioItem { IOType = IOType.InPut, WireName ="MX08B", EmName ="UnloadingElevatorMgzFootDual", StrdataName ="Unloading Elevator Mgz. Foot Dual"},
            new DioItem { IOType = IOType.InPut, WireName ="MX08C", EmName ="UnloadingElevatorStripStopperSingle", StrdataName ="Unloading Elevator Strip Stopper WorkSingle"},
            new DioItem { IOType = IOType.InPut, WireName ="MX08D", EmName ="UnloadingElevatorStripStopperDual", StrdataName ="Unloading Elevator Strip Stopper Dual"},
            new DioItem { IOType = IOType.InPut, WireName ="MX08E", EmName ="Spare112", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX08F", EmName ="Spare113", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX090", EmName ="Spare114", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX091", EmName ="Spare115", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX092", EmName ="EmptyMgzAlignerYSingle", StrdataName ="Empty Mgz. Aligner Y WorkSingle"},
            new DioItem { IOType = IOType.InPut, WireName ="MX093", EmName ="EmptyMgzAlignerYDual", StrdataName ="Empty Mgz. Aligner Y Dual"},
            new DioItem { IOType = IOType.InPut, WireName ="MX094", EmName ="Spare116", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX095", EmName ="Spare117", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX096", EmName ="Spare118", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX097", EmName ="Spare119", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX098", EmName ="Spare120", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX099", EmName ="Spare121", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX09A", EmName ="Spare122", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX09B", EmName ="Spare123", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX09C", EmName ="Spare124", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX09D", EmName ="Spare125", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX09E", EmName ="Spare126", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX09F", EmName ="Spare127", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A0", EmName ="Spare128", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A1", EmName ="Spare129", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A2", EmName ="VisionOK_Top", StrdataName ="Vision OK(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A3", EmName ="VisionBUSY_Top", StrdataName ="Vision BUSY(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A4", EmName ="VisionAlarm_Top", StrdataName ="Vision Alarm(Top)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A5", EmName ="Spare130", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A6", EmName ="Spare131", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A7", EmName ="Spare132", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A8", EmName ="Spare133", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0A9", EmName ="Spare134", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0AA", EmName ="VisionOK_Bottom", StrdataName ="Vision OK(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0AB", EmName ="VisionBUSY_Bottom", StrdataName ="Vision BUSY(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0AC", EmName ="VisionAlarm_Bottom", StrdataName ="Vision Alarm(Bottom)"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0AD", EmName ="Spare135", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0AE", EmName ="Spare136", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0AF", EmName ="Spare137", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B0", EmName ="Spare138", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B1", EmName ="Spare139", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B2", EmName ="Spare140", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B3", EmName ="Spare141", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B4", EmName ="Spare142", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B5", EmName ="Spare143", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B6", EmName ="Spare144", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B7", EmName ="Spare145", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B8", EmName ="Spare146", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0B9", EmName ="Spare147", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0BA", EmName ="Spare148", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0BB", EmName ="Spare149", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0BC", EmName ="Spare150", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0BD", EmName ="Spare151", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0BE", EmName ="Spare152", StrdataName ="Spare"},
            new DioItem { IOType = IOType.InPut, WireName ="MX0BF", EmName ="Spare153", StrdataName ="Spare"},

            new DioItem { IOType = IOType.OUTPut, WireName = "MY000", EmName = "Spare154", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY001", EmName = "Spare155", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY002", EmName = "LoadingElevatorMgzFootSingle", StrdataName = "Loading Elevator Mgz. Foot WorkSingle"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY003", EmName = "LoadingElevatorMgzFootDual", StrdataName = "Loading Elevator Mgz. Foot Dual"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY004", EmName = "Spare156", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY005", EmName = "Spare157", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY006", EmName = "Spare158", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY007", EmName = "Spare159", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY008", EmName = "Spare160", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY009", EmName = "Spare161", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY00A", EmName = "Spare162", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY00B", EmName = "Spare163", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY00C", EmName = "Spare164", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY00D", EmName = "Spare165", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY00E", EmName = "Spare166", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY00F", EmName = "Spare167", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY010", EmName = "Spare168", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY011", EmName = "Spare169", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY012", EmName = "UnloadingElevatorMgzFootSingle", StrdataName = "Unloading Elevator Mgz. Foot WorkSingle"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY013", EmName = "UnloadingElevatorMgzFootDual", StrdataName = "Unloading Elevator Mgz. Foot Dual"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY014", EmName = "UnloadingElevatorStripStopperSingle", StrdataName = "Unloading Elevator Strip Stopper WorkSingle"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY015", EmName = "Spare170", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY016", EmName = "Spare171", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY017", EmName = "Spare172", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY018", EmName = "Spare173", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY019", EmName = "Spare174", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY01A", EmName = "Spare175", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY01B", EmName = "Spare176", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY01C", EmName = "Spare177", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY01D", EmName = "Spare178", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY01E", EmName = "Spare179", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY01F", EmName = "Spare180", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY020", EmName = "Spare181", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY021", EmName = "Spare182", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY022", EmName = "VisionBankBit3_Top", StrdataName = "Vision Bank Bit3(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY023", EmName = "VisionReset_Top", StrdataName = "Vision Reset(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY024", EmName = "VisionBankBit4_Top", StrdataName = "Vision Bank Bit4(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY025", EmName = "VisionBankBit5_Top", StrdataName = "Vision Bank Bit5(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY026", EmName = "Spare183", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY027", EmName = "Spare184", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY028", EmName = "Spare185", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY029", EmName = "Spare186", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY02A", EmName = "VisionBankBit3_Bottom", StrdataName = "Vision Bank Bit3(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY02B", EmName = "VisionReset_Bottom", StrdataName = "Vision Reset(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY02C", EmName = "VisionBankBit4_Bottom", StrdataName = "Vision Bank Bit4(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY02D", EmName = "VisionBankBit5_Bottom", StrdataName = "Vision Bank Bit5(Bottom)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY02E", EmName = "Spare187", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY02F", EmName = "Spare188", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY030", EmName = "Spare189", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY031", EmName = "Spare190", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY032", EmName = "Spare191", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY033", EmName = "Spare192", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY034", EmName = "Spare193", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY035", EmName = "Spare194", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY036", EmName = "Spare195", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY037", EmName = "Spare196", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY038", EmName = "Spare197", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY039", EmName = "Spare198", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY03A", EmName = "Spare199", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY03B", EmName = "Spare200", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY03C", EmName = "Spare201", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY03D", EmName = "Spare202", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY03E", EmName = "Spare203", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY03F", EmName = "Spare204", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY040", EmName = "Spare205", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY041", EmName = "Spare206", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY042", EmName = "EmptyMgzAlignerYSingle", StrdataName = "Empty Mgz. Aligner Y WorkSingle"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY043", EmName = "Spare207", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY044", EmName = "Spare208", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY045", EmName = "Spare209", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY046", EmName = "Spare210", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY047", EmName = "Spare211", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY048", EmName = "Spare212", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY049", EmName = "Spare213", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY04A", EmName = "Spare214", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY04B", EmName = "Spare215", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY04C", EmName = "Spare216", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY04D", EmName = "Spare217", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY04E", EmName = "Spare218", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY04F", EmName = "Spare219", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY050", EmName = "Spare220", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY051", EmName = "Spare221", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY052", EmName = "Spare222", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY053", EmName = "Spare223", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY054", EmName = "Spare224", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY055", EmName = "Spare225", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY056", EmName = "Spare226", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY057", EmName = "Spare227", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY058", EmName = "Spare228", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY059", EmName = "Spare229", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY05A", EmName = "Spare230", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY05B", EmName = "Spare231", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY05C", EmName = "Spare232", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY05D", EmName = "Spare233", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY05E", EmName = "Spare234", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY05F", EmName = "Spare235", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY060", EmName = "Spare236", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY061", EmName = "Spare237", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY062", EmName = "Spare238", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY063", EmName = "Spare239", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY064", EmName = "Spare240", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY065", EmName = "Spare241", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY066", EmName = "Spare242", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY067", EmName = "Spare243", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY068", EmName = "Spare244", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY069", EmName = "Spare245", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY06A", EmName = "Spare246", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY06B", EmName = "Spare247", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY06C", EmName = "Spare248", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY06D", EmName = "Spare249", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY06E", EmName = "Spare250", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY06F", EmName = "Spare251", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY070", EmName = "Spare252", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY071", EmName = "Spare253", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY072", EmName = "Spare254", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY073", EmName = "Spare255", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY074", EmName = "Spare256", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY075", EmName = "Spare257", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY076", EmName = "Spare258", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY077", EmName = "Spare259", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY078", EmName = "Spare260", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY079", EmName = "Spare261", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY07A", EmName = "Spare262", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY07B", EmName = "Spare263", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY07C", EmName = "Spare264", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY07D", EmName = "Spare265", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY07E", EmName = "Spare266", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY07F", EmName = "Spare267", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY080", EmName = "Spare268", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY081", EmName = "Spare269", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY082", EmName = "Spare270", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY083", EmName = "Spare271", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY084", EmName = "Spare272", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY085", EmName = "Spare273", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY086", EmName = "Spare274", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY087", EmName = "Spare275", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY088", EmName = "Spare276", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY089", EmName = "Spare277", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY08A", EmName = "Spare278", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY08B", EmName = "Spare279", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY08C", EmName = "Spare280", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY08D", EmName = "Spare281", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY08E", EmName = "Spare282", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY08F", EmName = "Spare283", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY090", EmName = "Spare284", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY091", EmName = "Spare285", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY092", EmName = "Spare286", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY093", EmName = "Spare287", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY094", EmName = "Spare288", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY095", EmName = "Spare289", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY096", EmName = "Spare290", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY097", EmName = "Spare291", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY098", EmName = "Spare292", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY099", EmName = "Spare293", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY09A", EmName = "Spare294", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY09B", EmName = "Spare295", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY09C", EmName = "Spare296", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY09D", EmName = "Spare297", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY09E", EmName = "Spare298", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY09F", EmName = "Spare299", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A0", EmName = "Spare300", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A1", EmName = "Spare301", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A2", EmName = "VisionTrigger_Top", StrdataName = "Vision Trigger(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A3", EmName = "VisionBankBit0_Top", StrdataName = "Vision Bank Bit0(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A4", EmName = "VisionBankBit1_Top", StrdataName = "Vision Bank Bit1(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A5", EmName = "VisionBankBit2_Top", StrdataName = "Vision Bank Bit2(Top)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A6", EmName = "Spare302", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A7", EmName = "Spare303", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A8", EmName = "Spare304", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0A9", EmName = "Spare305", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0AA", EmName = "VisionTrigger_Bottom", StrdataName = "Vision Trigger(Btm)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0AB", EmName = "VisionBankBit0_Bottom", StrdataName = "Vision Bank Bit0(Btm)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0AC", EmName = "VisionBankBit1_Bottom", StrdataName = "Vision Bank Bit1(Btm)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0AD", EmName = "VisionBankBit2_Bottom", StrdataName = "Vision Bank Bit2(Btm)"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0AE", EmName = "Spare306", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0AF", EmName = "Spare307", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B0", EmName = "Spare308", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B1", EmName = "Spare309", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B2", EmName = "Spare310", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B3", EmName = "Spare311", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B4", EmName = "Spare312", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B5", EmName = "Spare313", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B6", EmName = "Spare314", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B7", EmName = "Spare315", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B8", EmName = "Spare316", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0B9", EmName = "Spare317", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0BA", EmName = "Spare318", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0BB", EmName = "Spare319", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0BC", EmName = "Spare320", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0BD", EmName = "Spare321", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0BE", EmName = "Spare322", StrdataName = "Spare"},
            new DioItem { IOType = IOType.OUTPut, WireName = "MY0BF", EmName = "Spare323", StrdataName = "Spare"}
        };
    }
}
