using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VSP_88D_CS.CONTROLLER
{
    public enum eDI
    {
        [Description("X000")]
        I_EmgSwFront,
        [Description("X001")]
        I_EmgSwRear,
        [Description("X002")]
        I_DoorFrontLeft,
        [Description("X003")]
        I_DoorFrontCenter,
        [Description("X004")]
        I_DoorFrontRight,
        [Description("X005")]
        I_DoorLeft,
        [Description("X006")]
        I_DoorRight,
        [Description("X007")]
        I_PumpOvld_Pm1,
        [Description("X008")]
        I_MainAirPressure,
        [Description("X009")]
        I_Gas1Pressure,
        [Description("X00A")]
        I_Gas2Pressure,
        [Description("X00B")]
        I_VacValveOpen_Pm1,
        [Description("X00C")]
        I_ECoolOn_Pm1,
        [Description("X00D")]
        I_MCoolOn_Pm1,
        [Description("X00E")]
        I_ChamberUp_Pm1,
        [Description("X00F")]
        I_ChamberDn_Pm1,
        [Description("X010")]
        I_PumpOilLevel_Pm1,
        [Description("X011")]
        I_LoadElevMgzChk_1,
        [Description("X012")]
        I_LoadElevMgzChk_2,
        [Description("X013")]
        I_LoadElevMgzChk_3,
        [Description("X014")]
        I_LoadElevMgzChk_4,
        [Description("X015")]
        I_Pusher1Overload,
        [Description("X016")]
        I_LoadElevStripChk_1,
        [Description("X017")]
        I_LoadElevStripChk_2,
        [Description("X018")]
        I_LoadElevStripChk_3,
        [Description("X019")]
        I_LoadElevStripChk_4,
        [Description("X01A")]
        I_InBufStopperUp,
        [Description("X01B")]
        I_InBufStopperDn,
        [Description("X01C")]
        I_InBufDevArrival_1,
        [Description("X01D")]
        I_InBufDevArrival_2,
        [Description("X01E")]
        I_InBufDevArrival_3,
        [Description("X01F")]
        I_InBufDevArrival_4,
        [Description("X020")]
        I_InBufCylFwd,
        [Description("X021")]
        I_InBufCylBwd,
        [Description("X022")]
        I_Pusher2Overload,
        [Description("X023")]
        I_Pusher2StripChk_1,
        [Description("X024")]
        I_Pusher2StripChk_2,
        [Description("X025")]
        I_Pusher2StripChk_3,
        [Description("X026")]
        I_Pusher2StripChk_4,
        [Description("X027")]
        I_Pusher2Up,
        [Description("X028")]
        I_Pusher2Dn,
        [Description("X029")]
        I_OutBufFwd,
        [Description("X02A")]
        I_OutBufBwd,
        [Description("X02B")]
        I_ChamberOutStripChk_1,
        [Description("X02C")]
        I_ChamberOutStripChk_2,
        [Description("X02D")]
        I_ChamberOutStripChk_3,
        [Description("X02E")]
        I_ChamberOutStripChk_4,
        [Description("X02F")]
        I_Pusher3Overload,
        [Description("X030")]
        I_Pusher3Up,
        [Description("X031")]
        I_Pusher3Dn,
        [Description("X032")]
        I_Pusher3Fwd,
        [Description("X033")]
        I_Pusher3Bwd,
        [Description("X034")]
        I_Pusher3DnEnable_1,
        [Description("X035")]
        I_Pusher3DnEnable_2,
        [Description("X036")]
        I_Pusher3DnEnable_3,
        [Description("X037")]
        I_Pusher3DnEnable_4,
        [Description("X038")]
        I_UnLoadElevStripChk_1,
        [Description("X039")]
        I_UnLoadElevStripChk_2,
        [Description("X03A")]
        I_UnLoadElevStripChk_3,
        [Description("X03B")]
        I_UnLoadElevStripChk_4,
        [Description("X03C")]
        I_UnLoadElevMgzChk_1,
        [Description("X03D")]
        I_UnLoadElevMgzChk_2,
        [Description("X03E")]
        I_UnLoadElevMgzChk_3,
        [Description("X03F")]
        I_UnLoadElevMgzChk_4,
        [Description("X040")]
        I_VisionOut,
        [Description("X041")]
        I_VisionEnable,
        [Description("X042")]
        I_VisionError,
        [Description("X043")]
        I_Gas3Pressure,
        [Description("X044")]
        I_Gas4Pressure,
        [Description("X045")]
        I_Pusher2Overload2,
        [Description("X046")]
        I_Pusher2Overload3,
        [Description("X047")]
        I_Pusher2Overload4,
        [Description("X048")]
        I_LoadElevMgzChk_5,
        [Description("X049")]
        I_LoadElevStripChk_5,
        [Description("X04A")]
        I_InBufDevArrival_5,
        [Description("X04B")]
        I_Pusher2StripChk_5,
        [Description("X04C")]
        I_ChamberOutStripChk_5,
        [Description("X04D")]
        I_Pusher3DnEnable_5,
        [Description("X04E")]
        I_UnLoadElevStripChk_5,
        [Description("X04F")]
        I_UnLoadElevMgzChk_5,
        [Description("X050")]
        I_LoadMgzTiltChk_1,
        [Description("X051")]
        I_LoadMgzTiltChk_2,
        [Description("X052")]
        I_LoadMgzTiltChk_3,
        [Description("X053")]
        I_LoadMgzTiltChk_4,
        [Description("X054")]
        I_UnldMgzTiltChk_1,
        [Description("X055")]
        I_UnldMgzTiltChk_2,
        [Description("X056")]
        I_UnldMgzTiltChk_3,
        [Description("X057")]
        I_UnldMgzTiltChk_4,
        [Description("X058")]
        I_IonizerAlarm,
        [Description("X059")]
        I_LaneFloatDetect,
        [Description("X05A")]
        I_Pusher1Overload2,
        [Description("X05B")]
        I_Pusher1Overload3,
        [Description("X05C")]
        I_Pusher1Overload4,
        [Description("X05D")]
        I_Pusher1Overload5,
        [Description("X05E")]
        I_Pusher2Overload5,
        [Description("X05F")]
        I_ChamberInEdge,
        [Description("X060")]
        I_ChamberOutEdge,
        [Description("X061")]
        I_Pusher3Overload2,
        [Description("X062")]
        I_Pusher3Overload3,
        [Description("X063")]
        I_Pusher3Overload4,
        [Description("X064")]
        I_Pusher3Overload5,
        [Description("X065")]
        I_N2Pressure_CJ,
        [Description("X066")]
        I_LoadElevMgzTiltCheck,
        [Description("X067")]
        I_UnldElevMgzTiltCheck,
        [Description("X068")]
        I_IonizerAlarm2,
        [Description("X069")]
        I_X069,
        [Description("X06A")]
        I_X06A,
        [Description("X06B")]
        I_X06B,
        [Description("X06C")]
        I_X06C,
        [Description("X06D")]
        I_X06D,
        [Description("X06E")]
        I_X06E,
        [Description("X06F")]
        I_X06F,
        MAX_DI,
    };

    public enum eDO
    {
        [Description("Y000")]
        O_TowerRed,
        [Description("Y001")]
        O_TowerGreen,
        [Description("Y002")]
        O_TowerYellow,
        [Description("Y003")]
        O_Buzzer,
        [Description("Y004")]
        O_RfPwrOn,
        [Description("Y005")]
        O_VPumpOn,
        [Description("Y006")]
        O_VValOpen,
        [Description("Y007")]
        O_GValOpen,
        [Description("Y008")]
        O_Mfc1Open,
        [Description("Y009")]
        O_Mfc2Open,
        [Description("Y00A")]
        O_ECoolOn,
        [Description("Y00B")]
        O_MCoolOn,
        [Description("Y00C")]
        O_N2Purge,
        [Description("Y00D")]
        O_AirPurge,
        [Description("Y00E")]
        O_RfOn,
        [Description("Y00F")]
        O_ServoPwrOn,
        [Description("Y010")]
        O_ChamberUp,
        [Description("Y011")]
        O_ChamberDn,
        [Description("Y012")]
        O_InBufStopperUp,
        [Description("Y013")]
        O_InBufStopperDn,
        [Description("Y014")]
        O_InBufFwd,
        [Description("Y015")]
        O_InBufBwd,
        [Description("Y016")]
        O_Pusher2Up,
        [Description("Y017")]
        O_Pusher2Dn,
        [Description("Y018")]
        O_OutBufFwd,
        [Description("Y019")]
        O_OutBufBwd,
        [Description("Y01A")]
        O_Pusher3Up,
        [Description("Y01B")]
        O_Pusher3Dn,
        [Description("Y01C")]
        O_Pusher3Fwd,
        [Description("Y01D")]
        O_Pusher3Bwd,
        [Description("Y01E")]
        O_NC,
        [Description("Y01F")]
        O_NC1,
        [Description("Y020")]
        O_InBufRollRun,
        [Description("Y021")]
        O_InBufRollSpd,
        [Description("Y022")]
        O_OutBufRollRun,
        [Description("Y023")]
        O_VisionTeach,
        [Description("Y024")]
        O_VisionTrig,
        [Description("Y025")]
        O_VisionBank1,
        [Description("Y026")]
        O_VisionBank2,
        [Description("Y027")]
        O_VisionBank3,
        [Description("Y028")]
        O_Mfc3Open,
        [Description("Y029")]
        O_Mfc4Open,
        [Description("Y02A")]
        O_VisionReset,
        [Description("Y02B")]
        O_NC8,
        [Description("Y02C")]
        O_NC9,
        [Description("Y02D")]
        O_NC10,
        [Description("Y02E")]
        O_NC11,
        [Description("Y02F")]
        O_NC12,
        [Description("Y030")]
        O_IonizerOn,
        [Description("Y031")]
        O_IonizerOn2,
        [Description("Y032")]
        O_DoorUnlockFrontCenter,
        [Description("Y033")]
        O_DoorUnlockFrontRight,
        [Description("Y034")]
        O_DoorUnlockLeft,
        [Description("Y035")]
        O_DoorUnlockRight,
        [Description("Y036")]
        O_Y036,
        [Description("Y037")]
        O_Y037,
        [Description("Y038")]
        O_Y038,
        [Description("Y039")]
        O_Y039,
        [Description("Y03A")]
        O_Y03A,
        [Description("Y03B")]
        O_Y03B,
        [Description("Y03C")]
        O_Y03C,
        [Description("Y03D")]
        O_Y03D,
        [Description("Y03E")]
        O_Y03E,
        [Description("Y03F")]
        O_Y03F,
        MAX_DO
    };

    public enum eAI
    {
        [Description("AI00")]
        AI_Mfc1_Pm1,
        [Description("AI01")]
        AI_Mfc2_Pm1,
        [Description("AI02")]
        AI_Vac_Pm1,
        [Description("AI03")]
        AI_RfRef_Pm1,
        [Description("AI04")]
        AI_RfFwd_Pm1,
        [Description("AI05")]
        AI_RfOnSts_Pm1,
        [Description("AI06")]
        AI_Mfc3_Pm1,
        [Description("AI07")]
        AI_Mfc4_Pm1,
        MAX_AI
    };

    public enum eAO
    {
        [Description("AO00")]
        AO_Mfc1_Pm1,
        [Description("AO01")]
        AO_Mfc2_Pm1,
        [Description("AO02")]
        AO_RfGenSv_Pm1,
        [Description("AO03")]
        AO_AY_03,
        [Description("AO04")]
        AO_Mfc3_Pm1,
        [Description("AO05")]
        AO_Mfc4_Pm1,
        MAX_AO
    }

    public enum eMtr
    {
        [Description("MT00")]
        Sm00_LoadElev_Z = 0,
        [Description("MT01")]
        Sm01_LoadPush_X,
        [Description("MT02")]
        Sm02_Index_X,
        [Description("MT03")]
        Sm03_UnldElev_Z,
        [Description("MT04")]
        Sm04_Inspect_Y,

        MAX_SERVO_AXIS
    }
}
